/**
 * Copyright Wattle LMS Contributors. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import { Lazy, RemovalPolicy } from 'aws-cdk-lib';
import {
  Distribution,
  KeyGroup,
  PublicKey,
  ViewerProtocolPolicy,
} from 'aws-cdk-lib/aws-cloudfront';
import { S3BucketOrigin } from 'aws-cdk-lib/aws-cloudfront-origins';
import { Grant, IGrantable } from 'aws-cdk-lib/aws-iam';
import { IKey, Key } from 'aws-cdk-lib/aws-kms';
import {
  BlockPublicAccess,
  Bucket,
  BucketEncryption,
  HttpMethods,
  IBucket,
  ObjectOwnership,
} from 'aws-cdk-lib/aws-s3';
import { Construct } from 'constructs';
import { suppressRules } from './checkov.js';
import { findCloudFrontDomainNames } from './cloudfront.js';
import { RsaKeyPairSecret } from './rsa-key-pair-secret/construct.js';
import { RuntimeConfig } from './runtime-config.js';
import { CloudfrontWebAcl } from './static-website.js';

export interface MediaBucketProps {
  /**
   * RuntimeConfig key used under the `s3` namespace.
   */
  readonly runtimeConfigKey: string;
  /**
   * Whether to encrypt the bucket with a customer-managed KMS key.
   *
   * @default true
   */
  readonly enableKmsEncryption?: boolean;
  /**
   * KMS key used to encrypt the bucket. Only used when `enableKmsEncryption`
   * is `true`. When not provided, a new key is created.
   */
  readonly encryptionKey?: IKey;
  /**
   * Whether the automatically created KMS key has rotation enabled. Only
   * applies when `enableKmsEncryption` is `true` and no `encryptionKey` is
   * supplied.
   *
   * @default true
   */
  readonly enableKeyRotation?: boolean;
  /**
   * Whether to protect the CloudFront distribution in front of the bucket
   * with an AWS WAF Web ACL.
   *
   * @default true
   */
  readonly enableWaf?: boolean;
  /**
   * Removal policy applied to the bucket when its stack is deleted.
   * `autoDeleteObjects` is only enabled when this is `RemovalPolicy.DESTROY`.
   *
   * @default RemovalPolicy.RETAIN
   */
  readonly removalPolicy?: RemovalPolicy;
}

/**
 * A private S3 bucket served through a CloudFront distribution (Origin
 * Access Control, so the bucket itself stays fully private) using signed
 * URLs for downloads, and presigned PUT URLs for uploads generated
 * server-side. Objects are never publicly readable or directly reachable
 * from S3.
 */
export class MediaBucket extends Construct {
  public readonly bucket: IBucket;
  public readonly cloudFrontDistribution: Distribution;
  private readonly signingKeyPairSecret: RsaKeyPairSecret;
  private allowedOrigins: string[] = ['*'];

  constructor(
    scope: Construct,
    id: string,
    {
      runtimeConfigKey,
      enableKmsEncryption = true,
      encryptionKey,
      enableKeyRotation = true,
      enableWaf = true,
      removalPolicy = RemovalPolicy.RETAIN,
    }: MediaBucketProps,
  ) {
    super(scope, id);

    const key: IKey | undefined = enableKmsEncryption
      ? (encryptionKey ?? new Key(this, 'EncryptionKey', { enableKeyRotation }))
      : undefined;

    this.bucket = new Bucket(this, runtimeConfigKey, {
      versioned: false,
      enforceSSL: true,
      encryption: key ? BucketEncryption.KMS : BucketEncryption.S3_MANAGED,
      encryptionKey: key,
      objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED,
      publicReadAccess: false,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      removalPolicy,
      autoDeleteObjects: removalPolicy === RemovalPolicy.DESTROY,
      cors: [
        {
          allowedMethods: [HttpMethods.PUT, HttpMethods.GET],
          allowedOrigins: Lazy.list({ produce: () => this.allowedOrigins }),
          allowedHeaders: ['*'],
          maxAge: 3000,
        },
      ],
    });
    suppressRules(
      this.bucket,
      ['CKV_AWS_18'],
      'Private, presigned-only bucket; server access logs are not required',
    );
    suppressRules(
      this.bucket,
      ['CKV_AWS_21'],
      'Every object is written to a unique, nonce-scoped path and never overwritten; versioning has no use here and only complicates deletion',
    );

    // CloudFront needs a PublicKey/KeyGroup pair to validate signed URLs;
    // the underlying RSA key pair is generated by a custom resource and its
    // private key held only in Secrets Manager (see RsaKeyPairSecret).
    this.signingKeyPairSecret = new RsaKeyPairSecret(this, 'SigningKeyPair');
    const signingPublicKey = new PublicKey(this, 'SigningPublicKey', {
      encodedKey: this.signingKeyPairSecret.publicKeyPem,
    });
    const signingKeyGroup = new KeyGroup(this, 'SigningKeyGroup', {
      items: [signingPublicKey],
    });

    const wafStack = enableWaf ? new CloudfrontWebAcl(this, 'waf') : undefined;

    this.cloudFrontDistribution = new Distribution(this, 'Distribution', {
      webAclId: wafStack?.wafArn,
      defaultBehavior: {
        origin: S3BucketOrigin.withOriginAccessControl(this.bucket),
        viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        trustedKeyGroups: [signingKeyGroup],
      },
    });
    // For SSE-KMS objects CloudFront also needs kms:Decrypt on the bucket's
    // key, or S3 returns AccessDenied even though the signature check passed.
    // withOriginAccessControl adds that grant to the key policy itself,
    // conditioned on any distribution in this account rather than this one:
    // naming this distribution there would make the key depend on the
    // distribution, which depends on the bucket, which depends on the key.
    // Reads stay limited to this distribution by the bucket policy's
    // s3:GetObject grant, which does name it.
    // See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-kms

    // See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DownloadDistValuesGeneral.html
    suppressRules(
      this.cloudFrontDistribution,
      ['CKV_AWS_174'],
      'Cloudfront default certificate does not use TLS 1.2',
    );
    suppressRules(
      this.cloudFrontDistribution,
      ['CKV_AWS_86'],
      'Access logs are not required for this internal media distribution',
    );

    RuntimeConfig.ensure(this).set('s3', runtimeConfigKey, {
      bucketName: this.bucket.bucketName,
      cloudFrontDomainName: this.cloudFrontDistribution.domainName,
      cloudFrontKeyPairId: signingPublicKey.publicKeyId,
      cloudFrontPrivateKeySecretArn: this.signingKeyPairSecret.secretArn,
    });
  }

  /**
   * Restricts the bucket's CORS configuration to the provided origins.
   *
   * @param origins - The origin strings, CloudFront distributions, or objects containing a CloudFront distribution to grant CORS from
   */
  public restrictCorsTo(
    ...origins: (
      | string
      | Distribution
      | { cloudFrontDistribution: Distribution }
    )[]
  ) {
    this.allowedOrigins = origins.flatMap((origin) =>
      typeof origin === 'string'
        ? [origin]
        : findCloudFrontDomainNames(
            'cloudFrontDistribution' in origin
              ? origin.cloudFrontDistribution
              : origin,
          ).map((domain) => `https://${domain}`),
    );
  }

  public grantPut(grantee: IGrantable): Grant {
    return this.bucket.grantPut(grantee);
  }

  /** Grants read access to the secret holding the CloudFront signing key pair's private key. */
  public grantReadSigningKey(grantee: IGrantable): Grant {
    return this.signingKeyPairSecret.grantReadSecret(grantee);
  }

  // Direct-IAM read, not the CloudFront-signed-URL path content is actually
  // served over -- for a Lambda that needs to enumerate this bucket's own
  // objects itself (e.g. listing a content item's HLS output before
  // deleting it), not for anything that ends up in front of a viewer.
  public grantRead(grantee: IGrantable): Grant {
    return this.bucket.grantRead(grantee);
  }

  public grantDelete(grantee: IGrantable): Grant {
    return this.bucket.grantDelete(grantee);
  }
}
