/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as AuthenticatedPreviewCourseCodeRouteImport } from './routes/_authenticated/preview/$courseCode'
import { Route as PublicCoursesCourseCodeRouteImport } from './routes/_public/courses/$courseCode'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedPreviewCourseCodeRoute =
  AuthenticatedPreviewCourseCodeRouteImport.update({
    id: '/preview/$courseCode',
    path: '/preview/$courseCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicCoursesCourseCodeRoute = PublicCoursesCourseCodeRouteImport.update({
  id: '/courses/$courseCode',
  path: '/courses/$courseCode',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/signin': typeof PublicSigninRoute
  '/preview/$courseCode': typeof AuthenticatedPreviewCourseCodeRoute
  '/courses/$courseCode': typeof PublicCoursesCourseCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/signin': typeof PublicSigninRoute
  '/preview/$courseCode': typeof AuthenticatedPreviewCourseCodeRoute
  '/courses/$courseCode': typeof PublicCoursesCourseCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_public/signin': typeof PublicSigninRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/preview/$courseCode': typeof AuthenticatedPreviewCourseCodeRoute
  '/_public/courses/$courseCode': typeof PublicCoursesCourseCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/preview/$courseCode'
    | '/courses/$courseCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/preview/$courseCode'
    | '/courses/$courseCode'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_public/signin'
    | '/_public/'
    | '/_authenticated/preview/$courseCode'
    | '/_public/courses/$courseCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/preview/$courseCode': {
      id: '/_authenticated/preview/$courseCode'
      path: '/preview/$courseCode'
      fullPath: '/preview/$courseCode'
      preLoaderRoute: typeof AuthenticatedPreviewCourseCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/courses/$courseCode': {
      id: '/_public/courses/$courseCode'
      path: '/courses/$courseCode'
      fullPath: '/courses/$courseCode'
      preLoaderRoute: typeof PublicCoursesCourseCodeRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedPreviewCourseCodeRoute: typeof AuthenticatedPreviewCourseCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedPreviewCourseCodeRoute: AuthenticatedPreviewCourseCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteChildren {
  PublicSigninRoute: typeof PublicSigninRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCoursesCourseCodeRoute: typeof PublicCoursesCourseCodeRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSigninRoute: PublicSigninRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCoursesCourseCodeRoute: PublicCoursesCourseCodeRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
